//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget_money_major
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Budget_money_major()
        {
            this.Budget_open_detail = new HashSet<Budget_open_detail>();
            this.Budget_receive_detail = new HashSet<Budget_receive_detail>();
            this.Budget_transfer_detail = new HashSet<Budget_transfer_detail>();
            this.Budget_transfer_detail1 = new HashSet<Budget_transfer_detail>();
        }
    
        public long budget_money_major_id { get; set; }
        public long budget_money_detail_id { get; set; }
        public string major_code { get; set; }
        public Nullable<decimal> budget_money_major_plan { get; set; }
        public Nullable<decimal> budget_money_major_contribute { get; set; }
        public Nullable<decimal> budget_money_major_use { get; set; }
        public string budget_money_major_comment { get; set; }
        public string c_created_by { get; set; }
        public Nullable<System.DateTime> d_created_date { get; set; }
        public string c_updated_by { get; set; }
        public Nullable<System.DateTime> d_updated_date { get; set; }
    
        public virtual Budget_money_detail Budget_money_detail { get; set; }
        public virtual Major Major { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget_open_detail> Budget_open_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget_receive_detail> Budget_receive_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget_transfer_detail> Budget_transfer_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget_transfer_detail> Budget_transfer_detail1 { get; set; }
    }
}
