//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget_transfer_head
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Budget_transfer_head()
        {
            this.Budget_transfer_detail = new HashSet<Budget_transfer_detail>();
        }
    
        public string budget_transfer_doc { get; set; }
        public string budget_doc_no { get; set; }
        public string budget_transfer_year { get; set; }
        public Nullable<System.DateTime> budget_transfer_date { get; set; }
        public string budget_type { get; set; }
        public string degree_code_from { get; set; }
        public string major_code_from { get; set; }
        public string budget_plan_code_from { get; set; }
        public string degree_code_to { get; set; }
        public string major_code_to { get; set; }
        public string budget_plan_code_to { get; set; }
        public string budget_transfer_remark { get; set; }
        public Nullable<decimal> budget_transfer_amount { get; set; }
        public string budget_transfer_status { get; set; }
        public string c_created_by { get; set; }
        public Nullable<System.DateTime> d_created_date { get; set; }
        public string c_updated_by { get; set; }
        public Nullable<System.DateTime> d_updated_date { get; set; }
    
        public virtual Budget_plan Budget_plan { get; set; }
        public virtual Budget_plan Budget_plan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget_transfer_detail> Budget_transfer_detail { get; set; }
        public virtual Degree Degree { get; set; }
        public virtual Degree Degree1 { get; set; }
        public virtual Major Major { get; set; }
        public virtual Major Major1 { get; set; }
    }
}
