//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget_receive_head
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Budget_receive_head()
        {
            this.Budget_receive_detail = new HashSet<Budget_receive_detail>();
            this.Deduct_head = new HashSet<Deduct_head>();
        }
    
        public string budget_receive_doc { get; set; }
        public Nullable<System.DateTime> budget_receive_date { get; set; }
        public string budget_receive_year { get; set; }
        public string budget_type { get; set; }
        public string budget_plan_code { get; set; }
        public string degree_code { get; set; }
        public Nullable<int> item_group_detail_id { get; set; }
        public Nullable<decimal> budget_receive_total { get; set; }
        public string budget_receive_comment { get; set; }
        public string c_created_by { get; set; }
        public Nullable<System.DateTime> d_created_date { get; set; }
        public string c_updated_by { get; set; }
        public Nullable<System.DateTime> d_updated_date { get; set; }
    
        public virtual Budget_plan Budget_plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget_receive_detail> Budget_receive_detail { get; set; }
        public virtual Item_group_detail Item_group_detail { get; set; }
        public virtual Degree Degree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deduct_head> Deduct_head { get; set; }
    }
}
