//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_status
    {
        public string person_code { get; set; }
        public string person_sex { get; set; }
        public string person_high { get; set; }
        public string person_width { get; set; }
        public string person_origin { get; set; }
        public string person_nation { get; set; }
        public string person_religion { get; set; }
        public Nullable<System.DateTime> person_birth { get; set; }
        public string person_marry { get; set; }
        public string c_created_by { get; set; }
        public Nullable<System.DateTime> d_created_date { get; set; }
        public string c_updated_by { get; set; }
        public Nullable<System.DateTime> d_updated_date { get; set; }
    }
}
