//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recv_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recv_item()
        {
            this.Deduct_detail = new HashSet<Deduct_detail>();
            this.Recv_detail = new HashSet<Recv_detail>();
        }
    
        public string recv_item_code { get; set; }
        public string recv_item_year { get; set; }
        public string recv_item_name { get; set; }
        public string recv_item_type { get; set; }
        public Nullable<decimal> recv_item_rate { get; set; }
        public string recv_item_remark { get; set; }
        public Nullable<bool> recv_item_is_director { get; set; }
        public string c_created_by { get; set; }
        public Nullable<System.DateTime> d_created_date { get; set; }
        public string c_updated_by { get; set; }
        public Nullable<System.DateTime> d_updated_date { get; set; }
        public string c_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deduct_detail> Deduct_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recv_detail> Recv_detail { get; set; }
    }
}
