//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usermenu
    {
        public int UserID { get; set; }
        public short MenuID { get; set; }
        public string CanView { get; set; }
        public string CanInsert { get; set; }
        public string CanEdit { get; set; }
        public string CanDelete { get; set; }
        public string CanApprove { get; set; }
        public string CanExtra { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
