//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Budget_plan
    {
        public string budget_plan_code { get; set; }
        public string budget_plan_year { get; set; }
        public string unit_code { get; set; }
        public string activity_code { get; set; }
        public string plan_code { get; set; }
        public string work_code { get; set; }
        public string fund_code { get; set; }
        public string c_active { get; set; }
        public string c_created_by { get; set; }
        public Nullable<System.DateTime> d_created_date { get; set; }
        public string c_updated_by { get; set; }
        public Nullable<System.DateTime> d_updated_date { get; set; }
        public string unit_name { get; set; }
        public string director_code { get; set; }
        public string director_name { get; set; }
        public string activity_name { get; set; }
        public string produce_code { get; set; }
        public string produce_name { get; set; }
        public string budget_code { get; set; }
        public string budget_name { get; set; }
        public string plan_name { get; set; }
        public string work_name { get; set; }
        public string fund_name { get; set; }
        public string director_sign_name { get; set; }
        public byte[] director_sign_image { get; set; }
        public string budget_type { get; set; }
    }
}
