//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Recv_detail
    {
        public string recv_doc_no { get; set; }
        public string recv_doc_ref { get; set; }
        public Nullable<System.DateTime> recv_date { get; set; }
        public string major_code { get; set; }
        public string degree_code { get; set; }
        public string recv_remark { get; set; }
        public Nullable<decimal> recv_total { get; set; }
        public Nullable<decimal> recv_reduce { get; set; }
        public string major_name { get; set; }
        public string major_abbrev { get; set; }
        public string major_year { get; set; }
        public Nullable<int> major_order { get; set; }
        public string degree_name { get; set; }
        public Nullable<int> item_group_detail_id { get; set; }
        public string item_group_detail_code { get; set; }
        public string item_group_detail_name { get; set; }
        public string item_group_code { get; set; }
        public string item_group_year { get; set; }
        public string item_group_name { get; set; }
        public string item_group_type { get; set; }
        public string recv_year { get; set; }
        public long recv_detail_id { get; set; }
        public string recv_item_code { get; set; }
        public Nullable<bool> recv_item_is_reduce { get; set; }
        public Nullable<decimal> recv_item_rate { get; set; }
        public Nullable<decimal> recv_item_debit { get; set; }
        public Nullable<decimal> recv_item_credit { get; set; }
        public string c_created_by { get; set; }
        public Nullable<System.DateTime> d_created_date { get; set; }
        public string c_updated_by { get; set; }
        public Nullable<System.DateTime> d_updated_date { get; set; }
        public string recv_item_name { get; set; }
        public string recv_item_type { get; set; }
        public Nullable<bool> recv_item_is_director { get; set; }
        public Nullable<decimal> recv_remain { get; set; }
        public string approve_head_status { get; set; }
        public string recv_item_remark { get; set; }
    }
}
