//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Budget_open_detail
    {
        public long budget_open_detail_id { get; set; }
        public string budget_open_doc { get; set; }
        public Nullable<long> budget_money_major_id { get; set; }
        public string budget_open_detail_remark { get; set; }
        public Nullable<decimal> budget_open_detail_amount { get; set; }
        public string c_created_by { get; set; }
        public Nullable<System.DateTime> d_created_date { get; set; }
        public string c_updated_by { get; set; }
        public Nullable<System.DateTime> d_updated_date { get; set; }
        public string budget_open_year { get; set; }
        public Nullable<System.DateTime> budget_open_date { get; set; }
        public Nullable<int> open_code { get; set; }
        public string open_title { get; set; }
        public string open_command_desc { get; set; }
        public string open_desc { get; set; }
        public string budget_type { get; set; }
        public string budget_plan_code { get; set; }
        public string degree_code { get; set; }
        public string major_code { get; set; }
        public string open_remark { get; set; }
        public Nullable<decimal> open_amount { get; set; }
        public string person_open { get; set; }
        public string approve_head_status { get; set; }
        public string budget_plan_year { get; set; }
        public string unit_code { get; set; }
        public string activity_code { get; set; }
        public string plan_code { get; set; }
        public string work_code { get; set; }
        public string fund_code { get; set; }
        public string unit_name { get; set; }
        public string director_code { get; set; }
        public string director_name { get; set; }
        public string activity_name { get; set; }
        public string produce_code { get; set; }
        public string produce_name { get; set; }
        public string budget_code { get; set; }
        public string budget_name { get; set; }
        public string plan_name { get; set; }
        public string work_name { get; set; }
        public string fund_name { get; set; }
        public string degree_name { get; set; }
        public long budget_money_detail_id { get; set; }
        public string budget_money_doc { get; set; }
        public Nullable<int> item_group_detail_id { get; set; }
        public string item_code { get; set; }
        public Nullable<int> item_detail_id { get; set; }
        public string item_name { get; set; }
        public string item_group_detail_code { get; set; }
        public string item_group_detail_name { get; set; }
        public string item_group_code { get; set; }
        public string item_group_name { get; set; }
        public string lot_code { get; set; }
        public string lot_name { get; set; }
        public string item_detail_code { get; set; }
        public string item_detail_name { get; set; }
        public string ef_open_doc { get; set; }
        public string major_name { get; set; }
        public string major_abbrev { get; set; }
        public Nullable<int> major_order { get; set; }
        public Nullable<int> material_id { get; set; }
        public string material_name { get; set; }
        public string material_detail { get; set; }
        public string item_group_type { get; set; }
        public string person_code { get; set; }
        public string title_code { get; set; }
        public string person_thai_name { get; set; }
        public string person_thai_surname { get; set; }
        public string budget_open_no { get; set; }
        public string budget_open_ap { get; set; }
        public string budget_open_pr { get; set; }
        public string budget_open_budget_no { get; set; }
        public Nullable<System.DateTime> budget_open_date_actual { get; set; }
    }
}
