//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Item_group_detail
    {
        public int item_group_detail_id { get; set; }
        public string item_group_detail_code { get; set; }
        public string item_group_detail_name { get; set; }
        public string item_group_code { get; set; }
        public string c_active { get; set; }
        public string c_created_by { get; set; }
        public Nullable<System.DateTime> d_created_date { get; set; }
        public string c_updated_by { get; set; }
        public string item_group_year { get; set; }
        public string item_group_name { get; set; }
        public string lot_code { get; set; }
        public string lot_year { get; set; }
        public string lot_name { get; set; }
        public string item_group_type { get; set; }
    }
}
