//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Budget_summary
    {
        public string budget_plan_code { get; set; }
        public string budget_money_year { get; set; }
        public string money_type { get; set; }
        public string money_type_name { get; set; }
        public string unit_code { get; set; }
        public string activity_code { get; set; }
        public string plan_code { get; set; }
        public string work_code { get; set; }
        public string fund_code { get; set; }
        public string unit_name { get; set; }
        public string director_code { get; set; }
        public string director_name { get; set; }
        public string activity_name { get; set; }
        public string produce_code { get; set; }
        public string produce_name { get; set; }
        public string budget_code { get; set; }
        public string budget_name { get; set; }
        public string plan_name { get; set; }
        public string work_name { get; set; }
        public string fund_name { get; set; }
        public string lot_code { get; set; }
        public string lot_name { get; set; }
        public string degree_code { get; set; }
        public string degree_name { get; set; }
        public string major_code { get; set; }
        public string major_name { get; set; }
        public string major_abbrev { get; set; }
        public Nullable<int> major_order { get; set; }
        public string budget_type { get; set; }
        public decimal budget_money_major_plan { get; set; }
    }
}
