//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Deduct_detail
    {
        public string deduct_doc_no { get; set; }
        public string deduct_year { get; set; }
        public Nullable<System.DateTime> deduct_date { get; set; }
        public string major_code { get; set; }
        public string degree_code { get; set; }
        public string recv_doc_no { get; set; }
        public Nullable<decimal> recv_total_remain { get; set; }
        public string budget_plan_code { get; set; }
        public string deduct_remark { get; set; }
        public string major_name { get; set; }
        public string major_abbrev { get; set; }
        public Nullable<int> major_order { get; set; }
        public string degree_name { get; set; }
        public string recv_doc_ref { get; set; }
        public Nullable<System.DateTime> recv_date { get; set; }
        public string recv_remark { get; set; }
        public Nullable<decimal> recv_total { get; set; }
        public Nullable<decimal> recv_reduce { get; set; }
        public Nullable<decimal> item_remain { get; set; }
        public Nullable<int> item_group_detail_id { get; set; }
        public string item_group_detail_code { get; set; }
        public string item_group_detail_name { get; set; }
        public string item_group_code { get; set; }
        public string item_group_year { get; set; }
        public string item_group_name { get; set; }
        public string item_group_type { get; set; }
        public string unit_code { get; set; }
        public string activity_code { get; set; }
        public string plan_code { get; set; }
        public string work_code { get; set; }
        public string fund_code { get; set; }
        public string unit_name { get; set; }
        public string director_code { get; set; }
        public string director_name { get; set; }
        public string activity_name { get; set; }
        public string produce_code { get; set; }
        public string produce_name { get; set; }
        public string budget_code { get; set; }
        public string budget_name { get; set; }
        public string plan_name { get; set; }
        public string work_name { get; set; }
        public string fund_name { get; set; }
        public string budget_type { get; set; }
        public long deduct_detail_id { get; set; }
        public string recv_item_code { get; set; }
        public Nullable<decimal> recv_item_rate { get; set; }
        public Nullable<bool> recv_item_is_director { get; set; }
        public string recv_item_remark { get; set; }
        public string c_created_by { get; set; }
        public Nullable<System.DateTime> d_created_date { get; set; }
        public string c_updated_by { get; set; }
        public Nullable<System.DateTime> d_updated_date { get; set; }
        public string recv_item_name { get; set; }
        public string recv_item_type { get; set; }
        public Nullable<decimal> Expr1 { get; set; }
        public string Expr2 { get; set; }
        public Nullable<bool> Expr3 { get; set; }
    }
}
