//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Person_all
    {
        public string person_code { get; set; }
        public string title_code { get; set; }
        public string person_thai_name { get; set; }
        public string person_thai_surname { get; set; }
        public string person_eng_name { get; set; }
        public string person_eng_surname { get; set; }
        public string person_nickname { get; set; }
        public string person_id { get; set; }
        public string person_pic { get; set; }
        public string c_created_by { get; set; }
        public Nullable<System.DateTime> d_created_date { get; set; }
        public string c_updated_by { get; set; }
        public Nullable<System.DateTime> d_updated_date { get; set; }
        public string position_code { get; set; }
        public string position_name { get; set; }
        public string person_level { get; set; }
        public string person_postionno { get; set; }
        public Nullable<System.DateTime> person_end { get; set; }
        public string person_group_code { get; set; }
        public string person_group_name { get; set; }
        public string person_manage_code { get; set; }
        public string person_manage_name { get; set; }
        public string budget_plan_code { get; set; }
        public string budget_plan_year { get; set; }
        public string unit_code { get; set; }
        public string activity_code { get; set; }
        public string plan_code { get; set; }
        public string work_code { get; set; }
        public string fund_code { get; set; }
        public string unit_name { get; set; }
        public string director_code { get; set; }
        public string director_name { get; set; }
        public string activity_name { get; set; }
        public string produce_code { get; set; }
        public string produce_name { get; set; }
        public string budget_code { get; set; }
        public string budget_name { get; set; }
        public string plan_name { get; set; }
        public string work_name { get; set; }
        public string fund_name { get; set; }
        public string person_work_status_code { get; set; }
        public string person_work_status_name { get; set; }
        public string title_name { get; set; }
        public string c_active { get; set; }
        public Nullable<System.DateTime> person_start { get; set; }
        public string level_position_name { get; set; }
        public string type_position_code { get; set; }
        public string type_position_name { get; set; }
        public string person_budget_type { get; set; }
        public string budget_type { get; set; }
        public string major_year { get; set; }
        public string major_name { get; set; }
        public string major_code { get; set; }
    }
}
