//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_User_group_menu
    {
        public string user_group_code { get; set; }
        public string CanView { get; set; }
        public string CanInsert { get; set; }
        public string CanEdit { get; set; }
        public string CanDelete { get; set; }
        public string CanApprove { get; set; }
        public string CanExtra { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string user_group_name { get; set; }
        public string MenuName { get; set; }
        public string MenuNavigationUrl { get; set; }
        public string MenuImageUrl { get; set; }
        public string MenuTarget { get; set; }
        public short MenuParent { get; set; }
        public Nullable<short> MenuOrder { get; set; }
        public string MenuCanView { get; set; }
        public string MenuCanInsert { get; set; }
        public string MenuCanEdit { get; set; }
        public string MenuCanDelete { get; set; }
        public string MenuCanApprove { get; set; }
        public string MenuCanExtra { get; set; }
        public string person_group_list { get; set; }
        public string director_lock { get; set; }
        public string unit_lock { get; set; }
        public string unit_code_list { get; set; }
        public string Menu_Status { get; set; }
        public string Remark { get; set; }
        public short MenuID { get; set; }
    }
}
