//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Budget_transfer_head
    {
        public string budget_transfer_doc { get; set; }
        public string budget_doc_no { get; set; }
        public string budget_transfer_year { get; set; }
        public Nullable<System.DateTime> budget_transfer_date { get; set; }
        public string budget_type { get; set; }
        public string degree_code_from { get; set; }
        public string major_code_from { get; set; }
        public string budget_plan_code_from { get; set; }
        public string budget_transfer_remark { get; set; }
        public Nullable<decimal> budget_transfer_amount { get; set; }
        public string c_created_by { get; set; }
        public Nullable<System.DateTime> d_created_date { get; set; }
        public string c_updated_by { get; set; }
        public Nullable<System.DateTime> d_updated_date { get; set; }
        public string degree_name_from { get; set; }
        public string major_name_from { get; set; }
        public string major_abbrev_from { get; set; }
        public Nullable<int> major_order_from { get; set; }
        public string unit_code_from { get; set; }
        public string activity_code_from { get; set; }
        public string plan_code_from { get; set; }
        public string work_code_from { get; set; }
        public string fund_code_from { get; set; }
        public string unit_name_from { get; set; }
        public string director_code_from { get; set; }
        public string director_name_from { get; set; }
        public string activity_name_from { get; set; }
        public string produce_code_from { get; set; }
        public string produce_name_from { get; set; }
        public string budget_code_from { get; set; }
        public string budget_name_from { get; set; }
        public string plan_name_from { get; set; }
        public string work_name_from { get; set; }
        public string fund_name_from { get; set; }
        public string degree_code_to { get; set; }
        public string major_code_to { get; set; }
        public string budget_plan_code_to { get; set; }
        public string degree_name_to { get; set; }
        public string major_name_to { get; set; }
        public string major_abbrev_to { get; set; }
        public Nullable<int> major_order_to { get; set; }
        public string unit_code_to { get; set; }
        public string activity_code_to { get; set; }
        public string plan_code_to { get; set; }
        public string work_code_to { get; set; }
        public string fund_code_to { get; set; }
        public string unit_name_to { get; set; }
        public string director_code_to { get; set; }
        public string director_name_to { get; set; }
        public string activity_name_to { get; set; }
        public string produce_code_to { get; set; }
        public string produce_name_to { get; set; }
        public string budget_code_to { get; set; }
        public string budget_name_to { get; set; }
        public string plan_name_to { get; set; }
        public string work_name_to { get; set; }
        public string fund_name_to { get; set; }
    }
}
